In [1]:
import numpy as np

In [2]:
M=[[26, -19],[-19, 14]]

In [3]:
M

[[26, -19], [-19, 14]]

In [6]:
M=np.array(M,dtype=np.float)

In [7]:
M[0]

array([ 26., -19.])

In [9]:
from numpy import linalg as LA 

In [22]:
x,y = LA.eig(M)

In [12]:
from sklearn import preprocessing

In [13]:
M_normalized = preprocessing.normalize(M, norm='l2')

In [18]:
E = [[6+np.sqrt(397), -19], [-19, -6+np.sqrt(397)]]

In [19]:
E

[[25.924858845171276, -19], [-19, 13.924858845171276]]

In [20]:
E_normalized = preprocessing.normalize(E, norm='l2')

In [21]:
E_normalized

array([[ 0.80657652, -0.59112969],
       [-0.80657652,  0.59112969]])

In [24]:
y[0]

array([0.80657652, 0.59112969])

In [25]:
y[0]*M

array([[ 20.97098954, -11.2314642 ],
       [-15.3249539 ,   8.27581573]])

In [26]:
d=[10,5,2,3]

In [27]:
np.sqrt(d)

array([3.16227766, 2.23606798, 1.41421356, 1.73205081])